# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


from filterKey import filtraceKlice
from filter_text import filtraceTextu
from make_matrix import make_matrix
from separate_letters import separate_letters
from gui_message_popup import showPopup
from check_even_length import check_even_length
from sifrovat import sifrovat
from desifrovat import desifrovat, finalize


class Ui_MainWindow(object):
    def __init__(self):
        self.key = None
        self.matrix = None
        self.language = "cz"
        self.separator = 'X'
        self.separator2 = 'Q'

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(836, 746)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nazev = QtWidgets.QLabel(self.centralwidget)
        self.nazev.setGeometry(QtCore.QRect(330, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.nazev.setFont(font)
        self.nazev.setObjectName("nazev")

        # sifrovani
        self.sifrovat_button = QtWidgets.QPushButton(self.centralwidget)
        self.sifrovat_button.setGeometry(QtCore.QRect(130, 310, 75, 24))
        self.sifrovat_button.setObjectName("sifrovat_button")
        self.sifrovat_button.clicked.connect(self.sifrovat)

        self.pole_opentext = QtWidgets.QTextEdit(self.centralwidget)
        self.pole_opentext.setGeometry(QtCore.QRect(70, 240, 201, 71))
        self.pole_opentext.setObjectName("pole_opentext")

        self.pole_filtr1_bigr = QtWidgets.QTextEdit(self.centralwidget)
        self.pole_filtr1_bigr.setGeometry(QtCore.QRect(70, 380, 201, 71))
        self.pole_filtr1_bigr.setReadOnly(True)
        self.pole_filtr1_bigr.setObjectName("pole_filtr1_bigr")

        self.pole_zasif_text_out = QtWidgets.QTextEdit(self.centralwidget)
        self.pole_zasif_text_out.setGeometry(QtCore.QRect(70, 500, 201, 71))
        self.pole_zasif_text_out.setReadOnly(True)
        self.pole_zasif_text_out.setObjectName("pole_zasif_text_out")

        # desifrovani
        self.desifrovat_button = QtWidgets.QPushButton(self.centralwidget)
        self.desifrovat_button.setGeometry(QtCore.QRect(630, 310, 75, 24))
        self.desifrovat_button.setObjectName("desifrovat_button")
        self.desifrovat_button.clicked.connect(self.desifrovat)

        self.pole_zasif_text_in = QtWidgets.QTextEdit(self.centralwidget)
        self.pole_zasif_text_in.setGeometry(QtCore.QRect(570, 240, 201, 71))
        self.pole_zasif_text_in.setObjectName("pole_zasif_text_in")
        self.pole_filtr2_bigr = QtWidgets.QTextEdit(self.centralwidget)
        self.pole_filtr2_bigr.setGeometry(QtCore.QRect(570, 380, 201, 71))
        self.pole_filtr2_bigr.setReadOnly(True)
        self.pole_filtr2_bigr.setObjectName("pole_filtr2_bigr")
        self.pole_desif_text = QtWidgets.QTextEdit(self.centralwidget)
        self.pole_desif_text.setGeometry(QtCore.QRect(570, 500, 201, 71))
        self.pole_desif_text.setReadOnly(True)
        self.pole_desif_text.setObjectName("pole_desif_text")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 220, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 360, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 480, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(620, 220, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(600, 360, 131, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(620, 480, 91, 16))
        self.label_6.setObjectName("label_6")
        self.pole_klic = QtWidgets.QTextEdit(self.centralwidget)
        self.pole_klic.setGeometry(QtCore.QRect(340, 110, 141, 31))
        self.pole_klic.setObjectName("pole_klic")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(370, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 160, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(610, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.button_vytvoritTab = QtWidgets.QPushButton(self.centralwidget)
        self.button_vytvoritTab.setGeometry(QtCore.QRect(360, 230, 101, 24))
        self.button_vytvoritTab.setObjectName("button_vytvoritTab")
        self.button_vytvoritTab.clicked.connect(self.test)

        self.checkbox_en = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_en.setGeometry(QtCore.QRect(350, 190, 61, 20))
        self.checkbox_en.setObjectName("checkbox_en")
        self.checkbox_en.clicked.connect(self.checkbox_en_clicked)

        self.checkbox_cz = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_cz.setGeometry(QtCore.QRect(430, 190, 70, 17))
        self.checkbox_cz.setObjectName("checkbox_cz")
        self.checkbox_cz.setChecked(True)
        self.checkbox_cz.clicked.connect(self.checkbox_cz_clicked)

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(380, 160, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")

        self.sifrovaci_tab = QtWidgets.QTextEdit(self.centralwidget)
        self.sifrovaci_tab.setGeometry(QtCore.QRect(360, 560, 121, 111))
        self.sifrovaci_tab.setReadOnly(True)
        self.sifrovaci_tab.setObjectName("sifrovaci_tab")

        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(370, 540, 81, 16))
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 836, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def test(self):
        entered_key = filtraceKlice(self.pole_klic.toPlainText(), self.language)
        if (entered_key == None):
            return showPopup("Minimální délka klíče musí být 4 neduplicitni znaky a bez čísel, zkus to znovu.", "Chyba klíče")
        self.key = entered_key
        self.matrix = make_matrix(self.key, self.language)
        self.sifrovaci_tab.setPlainText(str(self.matrix))

    def checkbox_cz_clicked(self):
        self.language = "cz"
        self.checkbox_en.setChecked(False)

    def checkbox_en_clicked(self):
        self.language = "en"
        self.checkbox_cz.setChecked(False)

    def sifrovat(self):
        if (self.matrix == None):
            return showPopup("Je zapotřebí zadat klíč a vytvořit matici.", "Chyba")
        entered_text = filtraceTextu(self.pole_opentext.toPlainText(), self.language)
        entered_text = separate_letters(entered_text, self.separator, self.separator2)
        entered_text = check_even_length(entered_text, self.separator, self.separator2)
        self.pole_filtr1_bigr.setPlainText(" ".join(entered_text[i:i + 2] for i in range(0, len(entered_text), 2)))
        self.pole_zasif_text_out.setPlainText(sifrovat(entered_text, self.matrix))

    def desifrovat(self):
        if (self.matrix == None):
            return showPopup("Je zapotřebí zadat klíč a vytvořit matici.", "Chyba")
        entered_text = self.pole_zasif_text_in.toPlainText()
        print(entered_text)
        desifrovany_text = desifrovat(entered_text.replace(" ", ""), self.matrix)
        self.pole_filtr2_bigr.setPlainText(" ".join(desifrovany_text[i:i + 2] for i in range(0, len(desifrovany_text), 2)))
        self.pole_desif_text.setPlainText(finalize(desifrovany_text, self.separator, self.separator2))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nazev.setText(_translate("MainWindow", "Playfair šifra"))
        self.sifrovat_button.setText(_translate("MainWindow", "Šifrovat"))
        self.desifrovat_button.setText(_translate("MainWindow", "Dešifrovat"))
        self.label.setText(_translate("MainWindow", "Text pro šifrování"))
        self.label_2.setText(_translate("MainWindow", "Vyfiltrovaný text a bigramy"))
        self.label_3.setText(_translate("MainWindow", "Zašifrovaný text"))
        self.label_4.setText(_translate("MainWindow", "Zašifrovaný text"))
        self.label_5.setText(_translate("MainWindow", "Vyfiltrovaný text a bigramy"))
        self.label_6.setText(_translate("MainWindow", "Dešifrovaný text"))
        self.label_7.setText(_translate("MainWindow", "Klíčové slovo"))
        self.label_8.setText(_translate("MainWindow", "Šifrování"))
        self.label_9.setText(_translate("MainWindow", "Dešifrování"))
        self.button_vytvoritTab.setText(_translate("MainWindow", "Vytvořit tabulku"))
        self.checkbox_en.setText(_translate("MainWindow", "Anglicky"))
        self.label_10.setText(_translate("MainWindow", "Zvol jazyk"))
        self.checkbox_cz.setText(_translate("MainWindow", "Česky"))
        self.label_11.setText(_translate("MainWindow", "Šifrovací tabulka"))
